server:
  port: 10049
  servlet:
    context-path: /jsmpeg-relay
  undertow:
    direct-buffers: true
    max-http-post-size: -1B
  ssl:
    enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    suffix: .htm
    cache: false
    mode: HTML
    servlet:
      content-type: text/html; charset=utf-8
  gson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    serialize-nulls: true
    pretty-printing: true

logging:
  path: /home/stgoder/jsmpeg-relay/logs
  file: /home/stgoder/jsmpeg-relay/logs/jsmpeg-relay.log
  level:
    root: INFO

myConfig:
  test-mode: true
  ffmpeg-path: /home/stgoder/jsmpeg-relay/ffmpeg.win
  pslog-path: /home/stgoder/jsmpeg-relay/pslog
  relay-server-port: 10047
  mpegts-server-port: 10048
  local-ipv4: 192.168.1.214
  ds:
    sqlite0:
      db-file-path: /home/stgoder/jsmpeg-relay/sqlite0.db
      pool-size: 3
      pool-name: sqlite0